blank_issues_enabled: true # å¯ç”¨ç©ºç™½é—®é¢˜
contact_links:
  - name: ğŸ’¬ é—®é¢˜ä¸è®¨è®º ğŸ’¬
    url: https://github.com/darkmatter2048/WindowsCleaner/discussions
    about: "ğŸ¤ æœ‰é—®é¢˜æˆ–æƒ³èŠå¤©ï¼Ÿæ¬¢è¿åŠ å…¥æˆ‘ä»¬å‹å¥½çš„ç¤¾åŒºè®¨è®ºï¼"

