name: 编译
run-name: 编译
on:
  workflow_dispatch:
    inputs:
      inno:
        description: "生成安装包"
        type: boolean
        default: false

jobs:
  Build:
    runs-on: windows-2022
    permissions: write-all
    steps:
      - name: 仓库检出
        uses: actions/checkout@v4
      - name: 设置 Python 3.10 #3.8 一直编译失败，只能改用3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -U nuitka==2.5.1 zstandard ordered-set
      - name: 编译
        run: python -m nuitka --mingw64 --assume-yes-for-downloads --standalone --windows-uac-admin --remove-output --windows-console-mode="disable" --jobs=8 --enable-plugins="pyqt5" --output-dir="dist" --main="main.py" --windows-icon-from-ico="icon.ico" --company-name="DaYe" --product-name="WindowsCleaner" --file-version="5.0.0" --product-version="5.0" --file-description="WindowsCleaner" --copyright="DaYe" --trademarks="DaYe"
      - name: 移动文件
        run: move WCMain dist/main.dist/WCMain
      - name: 上传文件
        uses: actions/upload-artifact@v4
        with:
          name: WindowsCleaner
          path: dist
      - name: 生成安装包
        if: ${{ inputs.inno }}
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.5
        with:
          path: script.iss
          options: /O+
      - name: 上传文件
        uses: actions/upload-artifact@v4
        with:
          name: WindowsCleaner-amd64-Setup
          path: releases/*.exe
