name: 编译
run-name: 编译
on:
  workflow_dispatch:
    inputs:
      inno:
        description: "生成安装包"
        type: boolean
        default: false
      sign:
        description: "签名"
        type: boolean
        default: false

jobs:
  Build:
    runs-on: windows-2022
    permissions: write-all
    steps:
      - name: 仓库检出
        uses: actions/checkout@v4
        
      - name: 设置 Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"
          
      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -U nuitka==2.5.1 zstandard ordered-set
          
      - name: 编译
        run: python -m nuitka --mingw64 --assume-yes-for-downloads --standalone --windows-uac-admin --remove-output --windows-console-mode="disable" --nofollow-imports --jobs=8 --enable-plugins="pyqt5" --output-dir="dist" --main="wincleaner.py" --windows-icon-from-ico="icon.ico" --company-name="DaYe" --product-name="WindowsCleaner" --file-version="5.0.0" --product-version="5.0" --file-description="WindowsCleaner" --copyright="DaYe" --trademarks="DaYe"
      - name: 移动文件
        run: move WCMain dist/wincleaner.dist/WCMain
        
      # 上传未签名的主程序用于代码签名
      - name: 上传未签名的主程序
        id: upload-unsigned-exe
        uses: actions/upload-artifact@v4
        with:
          name: unsigned-exe
          path: dist/wincleaner.dist/wincleaner.exe  # 根据实际路径调整
          
      # 提交代码签名请求
      - name: 提交代码签名请求
        if: ${{ inputs.sign }}
        id: submit-signing-request
        uses: signpath/github-action-submit-signing-request@v1.1
        with:
          api-token: ${{ secrets.SIGNPATH_API_TOKEN }}
          organization-id: ${{ secrets.SIGNPATH_ORGANIZATION_ID }}
          project-slug: "WindowsCleaner"  # 替换为实际项目slug
          signing-policy-slug: "test-signing"  # 替换为实际策略slug
          artifact-configuration-slug: "sign-exezip"
          github-artifact-id: ${{ steps.upload-unsigned-exe.outputs.artifact-id }}
          wait-for-completion: true
          output-artifact-directory: dist/wincleaner.dist  # 签名后文件输出路径
          
      - name: 上传文件
        uses: actions/upload-artifact@v4
        with:
          name: WindowsCleaner
          path: dist
          
      - name: 生成安装包
        if: ${{ inputs.inno }}
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.5
        with:
          path: script.iss
          options: /O+
          
      - name: 上传文件
        uses: actions/upload-artifact@v4
        with:
          name: WindowsCleaner-amd64-Setup
          path: releases/*.exe